[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "portfolio_market_risk"
version = "0.1.0"
description = "Sistema de monitoreo de riesgo de mercado de portafolio."
readme = "README.md"
requires-python = ">=3.9" 

dependencies = [
    "pandas",
    "alpaca-trade-api",
    "yfinance",
    "fredapi",
    "streamlit",
    "matplotlib",
    "python-dotenv"
]

[tool.setuptools.packages.find]
where = ["."]